# .sops.yaml
creation_rules:
  - path_regex: '(^|/)\.env(\..+)?$|(^|/)\.env\.sops$'
    age: age1ca4lzlnvd93wtdr250ru94sangcsss5p46r7662gppmx2v6ufaaqc6tujw
  - path_regex: '^ops/secrets/.*\.(ya?ml|json)$'
    age: age1ca4lzlnvd93wtdr250ru94sangcsss5p46r7662gppmx2v6ufaaqc6tujw
  - path_regex: '^config/.*\.(ya?ml|json)$'
    age: age1ca4lzlnvd93wtdr250ru94sangcsss5p46r7662gppmx2v6ufaaqc6tujw
