name: policy/enforcer
on: [pull_request]
jobs:
  policy-enforcer:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup GitHub CLI
        run: |
          # Install GitHub CLI
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      - uses: tj-actions/changed-files@v45
        id: cf
      - name: Block bot on protected paths
        run: |
          # Input validation - ensure we have changed files
          if [ -z "${{ steps.cf.outputs.all_changed_files }}" ]; then
            echo "No files changed, skipping validation"
            exit 0
          fi
          
          # Define protected paths pattern
          PROTECTED='^(\.github/workflows/|ops/|contracts/|db/migrations/|infra/|Dockerfile|docker/|package(-lock)?\.json)'
          
          # Validate each changed file
          for f in ${{ steps.cf.outputs.all_changed_files }}; do
            if [[ "$f" =~ $PROTECTED ]] && [[ "${{ github.actor }}" == "quantapilot-bot" ]]; then
              echo "❌ Bot cannot change protected file: $f"
              echo "Protected paths require human approval and proper labels"
              exit 1
            fi
          done
          
          echo "✅ No protected path violations detected"
      - name: Require label for workflow edits
        if: contains(steps.cf.outputs.all_changed_files, '.github/workflows/')
        run: |
          # Validate PR exists and has labels
          if [ -z "${{ github.event.pull_request.number }}" ]; then
            echo "❌ Cannot determine PR number"
            exit 1
          fi
          
          # Check for required label
          echo "Checking PR labels..."
          echo "PR Number: ${{ github.event.pull_request.number }}"
          
          # Authenticate with GitHub CLI using GITHUB_TOKEN
          echo "${{ github.token }}" | gh auth login --with-token
          
          # Get PR labels
          LABELS=$(gh pr view ${{ github.event.pull_request.number }} --json labels -q '.labels[].name' 2>/dev/null || echo "")
          echo "PR Labels: $LABELS"
          
          if echo "$LABELS" | grep -qx 'ops:workflow-change'; then
            echo "✅ Required label 'ops:workflow-change' found"
          else
            echo "❌ Missing required label 'ops:workflow-change'"
            echo "Workflow changes require the 'ops:workflow-change' label and proper approvals"
            exit 1
          fi
