version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quantapilot
      POSTGRES_USER: qp
      POSTGRES_PASSWORD: qp
    ports: ['5432:5432']
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${PWD}/ops/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  pgdata: {}
